Update db-migrator to include ability to deal with partial installs
Allow user to upgrade or downgrade form a release that did not complete successfully

Issue-ID: POLICY-3490
Change-Id: Ie14a744246f26a9036066b9f4064bca0c23290be
Signed-off-by: ktimoney <kevin.timoney@est.tech>

diff --git a/policy-db-migrator/src/main/docker/db-migrator b/policy-db-migrator/src/main/docker/db-migrator
--- a/policy-db-migrator/src/main/docker/db-migrator
+++ b/policy-db-migrator/src/main/docker/db-migrator
@@ -324,6 +324,87 @@ function previous_release
 }
 
 #####################################################
+# object_exists
+#####################################################
+
+function object_exists
+{
+    if [ "${DEBUG}" = "y" ]; then
+        echo "-- object_exists --"
+        set -x
+    fi
+
+    local sqlFile="${1}"
+    local query rc objectType objectName
+
+    objectName=$(basename ${sqlFile} .sql | cut -f2 -d-)
+
+    rc=$(cat ${sqlFile} | awk '/ALTER/ && /CONSTRAINT/' | wc -l)
+    if [ $rc -gt 0 ]; then
+         objectType="constraint"
+    else
+        rc=$(cat ${sqlFile} | awk '/INDEX/' | wc -l)
+        if [ $rc -gt 0 ]; then
+             objectType="index"
+        else
+             objectType="table"
+        fi
+    fi
+
+    if [ "${objectType}" == "constraint" ]; then
+          query="SELECT IF (constraint_count>0, TRUE, FALSE) as constraint_exists FROM "
+          query=${query}"(SELECT count(1) as constraint_count from INFORMATION_SCHEMA.TABLE_CONSTRAINTS "
+          query=${query}"WHERE lower(constraint_name)=lower('${objectName}') AND table_schema='${SCHEMA}') t"
+    elif [ "${objectType}" == "index" ]; then
+          query="SELECT IF (index_count>0, TRUE, FALSE) as index_exists FROM "
+          query=${query}"(SELECT count(1) as index_count FROM INFORMATION_SCHEMA.STATISTICS "
+          query=${query}"WHERE lower(index_name)=lower('${objectName}') AND index_schema='${SCHEMA}') t"
+    else
+          query="SELECT IF (table_count>0, TRUE, FALSE) as table_exists FROM "
+          query=${query}"(SELECT count(1) as table_count FROM INFORMATION_SCHEMA.TABLES "
+          query=${query}"WHERE lower(table_name)=lower('${objectName}') AND table_schema='${SCHEMA}') t"
+    fi
+
+    rc=$(${MYSQL} --skip-column-names --silent --execute "${query}")
+
+    return $rc;
+}
+
+#####################################################
+# last_operation_status
+#####################################################
+
+function last_operation_status
+{
+    if [ "${DEBUG}" = "y" ]; then
+        echo "-- last_operation_status --"
+        set -x
+    fi
+
+    local query rc row
+
+    query="SELECT script, operation, from_version, to_version, success FROM  "
+    query=${query}"${METADATA_HISTORY} WHERE id="
+    query=${query}"(SELECT MAX(id) from ${METADATA_HISTORY}) "
+    query=${query}"AND success=0"
+
+    row=$(${MYSQL} --skip-column-names --silent --execute "${query}")
+
+    if [ "${row}" != "" ]; then
+        LAST_SCRIPT=$(echo $row | awk -F'  *' '{print $1}')
+        LAST_OPERATION=$(echo $row | awk -F'  *' '{print $2}')
+        LAST_FROM_VERSION=$(echo $row | awk -F'  *' '{print $3}')
+        LAST_TO_VERSION=$(echo $row | awk -F'  *' '{print $4}')
+        LAST_STATUS=$(echo $row | awk -F'  *' '{print $5}')
+        rc=0
+    else
+        rc=1
+    fi
+
+    return $rc;
+}
+
+#####################################################
 # execute sql script history
 #####################################################
 
@@ -387,10 +468,26 @@ function upgrade
         set -x
     fi
 
-    local sqlName sqlFile schemaVersion upgradeSqls rc tagDate tag
+    local sqlName sqlFile schemaVersion upgradeSqls rc tagDate tag retry compare
     tagDate=$(date +%d%m%y%H%M%S)
+    retry=0
 
     echo "upgrade: ${CURRENT_RELEASE} -> ${TARGET_UPGRADE_RELEASE}"
+    last_operation_status
+    rc=$?
+    if [ $rc -eq 0 ]; then
+         echo "Partial $LAST_OPERATION detected"
+         retry=1
+         if [ "${LAST_OPERATION}" == 'upgrade' ]; then
+              CURRENT_RELEASE="${LAST_FROM_VERSION}"
+              compare=lt
+              echo "Upgrade will attempt to resume at $LAST_SCRIPT"
+         else
+              CURRENT_RELEASE="${LAST_TO_VERSION}"
+              compare=le
+              echo "Upgrade will attempt to resume after $LAST_SCRIPT"
+         fi
+    fi
 
     if [ ${CURRENT_RELEASE} \< ${TARGET_UPGRADE_RELEASE} ]; then
         upgradeSqls=$(ls -v "${UPGRADE_DIR}"/*/upgrade/*.sql 2> /dev/null)
@@ -401,12 +498,24 @@ function upgrade
             if [ "${schemaVersion}" -gt "${CURRENT_RELEASE}" ] && \
                 [ "${schemaVersion}" -le "${TARGET_UPGRADE_RELEASE}" ]; then
                 tag=${tagDate}"${schemaVersion}u"
-                run_script "upgrade" "${sqlName}" "${sqlFile}" "${PREVIOUS_RELEASE}" "${schemaVersion}" "${tag}"
-                rc=$?
-                if [ ${rc} -ne 0 ]; then
-                    echo "${SCHEMA}: upgrade aborted at ${schemaVersion} by script ${sqlName}"
-                    set_current_release "${schemaVersion}"
-                    return ${rc}
+                if [ $retry -eq 1 ] && \
+                    [ $(echo ${sqlName}| awk -F- '{print $1}') -${compare} $(echo ${LAST_SCRIPT}| awk -F- '{print $1}') ]; then
+                     rc=1
+                else
+                     rc=0
+                fi
+                if [ ${rc} -eq 0 ]; then
+                     object_exists ${sqlFile}
+                     rc=$?
+                     if [ ${rc} -eq 0 ]; then
+                         run_script "upgrade" "${sqlName}" "${sqlFile}" "${PREVIOUS_RELEASE}" "${schemaVersion}" "${tag}"
+                         rc=$?
+                         if [ ${rc} -ne 0 ]; then
+                             echo "${SCHEMA}: upgrade aborted at ${schemaVersion} by script ${sqlName}"
+                             set_current_release "${schemaVersion}"
+                             return ${rc}
+                         fi
+                     fi
                 fi
             fi
         done
@@ -428,10 +537,26 @@ function downgrade
         set -x
     fi
 
-    local sqlName sqlFile schemaVersion downgradeSqls rc tagDate tag
+    local sqlName sqlFile schemaVersion downgradeSqls rc tagDate tag retry compare
     tagDate=$(date +%d%m%y%H%M%S)
+    retry=0
 
     echo "downgrade: ${CURRENT_RELEASE} -> ${TARGET_DOWNGRADE_RELEASE}"
+    last_operation_status
+    rc=$?
+    if [ $rc -eq 0 ]; then
+         echo "Partial $LAST_OPERATION detected"
+         retry=1
+         if [ "${LAST_OPERATION}" == 'downgrade' ]; then
+              CURRENT_RELEASE="${LAST_FROM_VERSION}"
+              compare=gt
+              echo "Downgrade will attempt to resume at $LAST_SCRIPT"
+         else
+              CURRENT_RELEASE="${LAST_TO_VERSION}"
+              compare=ge
+              echo "Downgrade will attempt to resume before $LAST_SCRIPT"
+         fi
+    fi
 
     if [ ${CURRENT_RELEASE} \> ${TARGET_DOWNGRADE_RELEASE} ]; then
         downgradeSqls=$(ls -v -r "${DOWNGRADE_DIR}"/*/downgrade/*.sql 2> /dev/null)
@@ -441,12 +566,24 @@ function downgrade
             if [ "${schemaVersion}" -le "${CURRENT_RELEASE}" ] && \
                 [ "${schemaVersion}" -gt "${TARGET_DOWNGRADE_RELEASE}" ]; then
                 tag=${tagDate}"${schemaVersion}d"
-                run_script "downgrade" "${sqlName}" "${sqlFile}" "${schemaVersion}" "${PREVIOUS_RELEASE}" ${tag}
-                rc=$?
-                if [ ${rc} -ne 0 ]; then
-                    echo "${SCHEMA}: downgrade aborted at ${schemaVersion} by script ${sqlName}"
-                    set_current_release "${schemaVersion}"
-                    return ${rc}
+                if [ $retry -eq 1 ] && \
+                    [ $(echo ${sqlName}| awk -F- '{print $1}') -${compare} $(echo ${LAST_SCRIPT}| awk -F- '{print $1}') ]; then
+                     rc=1
+                else
+                     rc=0
+                fi
+                if [ ${rc} -eq 0 ]; then
+                     object_exists ${sqlFile}
+                     rc=$?
+                     if [ ${rc} -eq 1 ]; then
+                         run_script "downgrade" "${sqlName}" "${sqlFile}" "${schemaVersion}" "${PREVIOUS_RELEASE}" ${tag}
+                         rc=$?
+                         if [ ${rc} -ne 0 ]; then
+                             echo "${SCHEMA}: downgrade aborted at ${schemaVersion} by script ${sqlName}"
+                             set_current_release "${schemaVersion}"
+                             return ${rc}
+                         fi
+                     fi
                 fi
             fi
         done
